"""Run the example catalog and report claimed vs computed."""

from __future__ import annotations

import dataclasses
import json
import traceback
from pathlib import Path

from .. import networks
from ..pipeline import conley_morse_graph
from ..spec import LEGACY, PAPER, Spec
from .catalog import EXAMPLES, Example

REPORTS = Path(__file__).resolve().parents[3] / "reports"


@dataclasses.dataclass
class ExampleOutcome:
    label: str
    source: str
    spec: str
    level: int
    seconds: float
    claimed_seconds: float | None
    results: list[tuple[str, object, object, bool]]
    error: str | None = None
    #: Summary of what was computed, whether or not a claim covers it.
    summary: dict = dataclasses.field(default_factory=dict)

    @property
    def ok(self) -> bool:
        return self.error is None and all(r[3] for r in self.results)

    @property
    def checked(self) -> int:
        return len(self.results)

    @property
    def failed(self) -> list[tuple]:
        return [r for r in self.results if not r[3]]


def _summary(result) -> dict:
    return {
        "morse_nodes": len(result.nodes),
        "conley_indices": {str(k): list(v) for k, v in sorted(result.conley_indices.items())},
        "trivial_index_nodes": result.trivial_index_nodes,
        "stable_nodes": result.stable_nodes,
        "morse_edges": sorted(result.edges),
        "top_cell_counts": {str(k): v for k, v in sorted(result.top_cell_counts.items())},
        "index_set": [k + 1 for k in result.stg.num_thresholds],
        "stg_vertices": len(list(result.stg.digraph.vertices())),
        "stg_edges": len(list(result.stg.digraph.edges())),
        "diagnostics": dict(result.diagnostics),
    }


def run_example(example: Example, spec: Spec = LEGACY) -> ExampleOutcome:
    try:
        if example.is_ramp:
            system = networks.RAMP_SYSTEMS[example.ramp_system]
            labelling, num_thresholds = system.wall_labelling()
            result = conley_morse_graph(
                labelling=labelling,
                num_thresholds=num_thresholds,
                spec=spec,
                level=example.level,
            )
        else:
            result = conley_morse_graph(
                networks.parameter(example.network, example.index),
                spec=spec,
                level=example.level,
            )
    except Exception:
        return ExampleOutcome(
            label=example.label,
            source=example.source,
            spec=spec.name,
            level=example.level,
            seconds=0.0,
            claimed_seconds=example.claimed_seconds,
            results=[],
            error=traceback.format_exc(limit=3),
        )

    results = []
    for check in example.checks:
        try:
            results.append(check(result))
        except Exception as exc:  # a check that cannot even run is a failure
            results.append((f"{check.__name__} raised", "-", repr(exc), False))

    return ExampleOutcome(
        label=example.label,
        source=example.source,
        spec=spec.name,
        level=example.level,
        seconds=result.seconds,
        claimed_seconds=example.claimed_seconds,
        results=results,
        summary=_summary(result),
    )


def run_all(
    specs=(LEGACY, PAPER),
    *,
    include_expensive: bool = True,
    only: list[str] | None = None,
) -> list[ExampleOutcome]:
    outcomes: list[ExampleOutcome] = []
    for example in EXAMPLES:
        if only and example.label not in only:
            continue
        if example.expensive and not include_expensive:
            print(f"[examples] skipping {example.label} (expensive)")
            continue
        for spec in specs:
            print(f"[examples] {example.label} spec={spec.name} ...", flush=True)
            outcome = run_example(example, spec)
            status = "ok" if outcome.ok else ("ERROR" if outcome.error else "MISMATCH")
            print(
                f"           {status}  {outcome.seconds:.2f}s  "
                f"{sum(1 for r in outcome.results if r[3])}/{outcome.checked} checks"
            )
            outcomes.append(outcome)
    return outcomes


def render(outcomes: list[ExampleOutcome]) -> str:
    out: list[str] = []
    out.append("# Reproduction of the monograph's computational examples\n")
    out.append(
        "Generated by `python -m rookfields.examples`. `legacy` reproduces "
        "`DSGRN_utils` bit-for-bit; `paper` applies the live manuscript "
        "definitions (see `divergence.md`).\n"
    )
    out.append(
        "Runtimes quoted in the text were measured by the authors on a laptop "
        "using one core (`examples4.tex:32`); the column is context, not a "
        "claim under test.\n"
    )

    by_label: dict[str, list[ExampleOutcome]] = {}
    for o in outcomes:
        by_label.setdefault(o.label, []).append(o)

    # -- headline table ------------------------------------------------
    out.append("## Summary\n")
    out.append("| example | source | level | spec | checks passed | runtime | claimed |")
    out.append("|---|---|---:|---|---|---:|---:|")
    for label, group in by_label.items():
        for o in group:
            passed = sum(1 for r in o.results if r[3])
            if o.error:
                cell = "**ERROR**"
            elif not o.results:
                cell = "_no numeric claim_"
            else:
                cell = f"{passed}/{o.checked}" + ("" if o.ok else "  **MISMATCH**")
            claimed = f"{o.claimed_seconds:.2f}s" if o.claimed_seconds else "-"
            out.append(
                f"| `{label}` | `{o.source}` | {o.level} | {o.spec} | {cell} | "
                f"{o.seconds:.2f}s | {claimed} |"
            )

    # -- per-example detail --------------------------------------------
    out.append("\n## Detail\n")
    for label, group in by_label.items():
        out.append(f"\n### `{label}`\n")
        out.append(f"Source: `{group[0].source}`, level {group[0].level}.\n")
        for o in group:
            out.append(f"\n**spec = `{o.spec}`** ({o.seconds:.2f} s)\n")
            if o.error:
                out.append("```\n" + o.error + "```\n")
                continue
            if o.results:
                out.append("| quantity | claimed | computed | |")
                out.append("|---|---|---|:-:|")
                for name, claimed, computed, ok in o.results:
                    mark = "ok" if ok else "**X**"
                    out.append(f"| {name} | `{claimed}` | `{computed}` | {mark} |")
            else:
                out.append("_No numeric claim in the text to check._\n")
            s = o.summary
            out.append(
                f"\nComputed: {s['morse_nodes']} Morse nodes, "
                f"index set {s['index_set']}, "
                f"{s['stg_vertices']} STG vertices / {s['stg_edges']} edges. "
                f"Conley indices: `{s['conley_indices']}`.\n"
            )
            if s.get("diagnostics"):
                out.append(f"Diagnostics: `{s['diagnostics']}`\n")

    return "\n".join(out) + "\n"


def main(argv=None) -> int:
    import argparse

    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--spec", default="both", choices=["legacy", "paper", "both"])
    parser.add_argument("--only", action="append", help="restrict to these labels")
    parser.add_argument(
        "--skip-expensive",
        action="store_true",
        help="skip the two 6-node EMT runs (about 2 minutes each, per spec)",
    )
    parser.add_argument("--out", type=Path, default=REPORTS / "examples.md")
    parser.add_argument("--json", type=Path, default=REPORTS / "examples.json")
    args = parser.parse_args(argv)

    specs = {"legacy": (LEGACY,), "paper": (PAPER,), "both": (LEGACY, PAPER)}[args.spec]
    outcomes = run_all(
        specs=specs, include_expensive=not args.skip_expensive, only=args.only
    )

    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text(render(outcomes))
    args.json.write_text(
        json.dumps([dataclasses.asdict(o) for o in outcomes], indent=2, default=str)
    )
    mismatched = [o for o in outcomes if not o.ok]
    print(f"\nwrote {args.out}\nwrote {args.json}")
    print(f"{len(outcomes) - len(mismatched)}/{len(outcomes)} runs fully matched")
    for o in mismatched:
        print(f"  - {o.label} [{o.spec}]: " + ("error" if o.error else f"{len(o.failed)} mismatched"))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
