"""The regulatory networks and ramp systems used in the monograph.

Network specifications are taken from the authors' own notebook
``code/Chapter16_adapted.ipynb`` and cross-checked against the parameter-graph
sizes quoted in the text.  All four large networks reproduce their stated sizes
exactly:

    N3_A   87,280,405,632   examples4.tex:265   fig:3d_example_1RN
    N3_B        3,600,000   examples4.tex:437   fig:example_1_3d_network
    N5     13,608,000,000   examples4.tex:981   fig:network_5D
    N6_EMT  4,429,771,960,320  examples4.tex:665  fig:RN

Ramp-system parameters come from ``tab:parameters_van_der_pol_ramp_system``
(examples4.tex:857-869) and ``tab:parameters_ramp_system_intro_periodic``
(introduction6.tex:525-541).
"""

from __future__ import annotations

import dataclasses
from functools import lru_cache

import DSGRN
from DSGRN_utils.RampFunction import ramp_function
from DSGRN_utils.WallLabelling import ramp_system_wall_labelling

# ---------------------------------------------------------------------------
# DSGRN regulatory networks
# ---------------------------------------------------------------------------

NETWORKS: dict[str, str] = {
    # fig:example_2_2d_network (examples4.tex:70-83): 1 self-activates, 1 -| 2,
    # 2 -> 1, 2 self-activates.  |PG| = 1600.  Carries nodes 752 and 47.
    "N2_a": "1 : 1 + 2\n2 : (~1) 2",
    # fig:network_2_intro(A) / ex:RNDSGRN (RampSystemsv4.tex:976).  |PG| = 1600.
    # Carries node 974 (ex:mccord); R(974) gives the running wall labelling of
    # fig:wall_labeling(A).
    "N2_b": "1 : (~1)(~2)\n2 : (~1)(~2)",
    # fig:3d_example_1RN.  Carries 52,718,681,992 / 65,571,607,721 / 52,717,613,010.
    "N3_A": "1 : 1+2+3\n2 : (~1)(2+3)\n3 : (~2)(1+3)",
    # fig:example_1_3d_network.  Carries 2,472,287 / 2,472,286 / 2,023,186.
    "N3_B": "1 : (1)(~2)(~3)\n2 : (~1)(2)\n3 : (~2)(3)",
    # fig:network_5D.  Carries 5,103,162,287.
    "N5": "1 : 1(~2)(~3)\n2 : (~1)(2)\n3 : (~2)(3)\n4 : (2)\n5 : (3)(4)(5)",
    # fig:RN, the six-node EMT network (TGFb, miR200, Snail1, Ovol2, Zeb1, miR34a).
    # Carries 2,684,686,006 and 1,739,757,491,101.
    "N6_EMT": (
        "1 : (~2)(~4)\n2 : (~3)(~5)\n3 : (1)(~3)(~6)\n"
        "4 : (~5)\n5 : (~2)(~4)(3)\n6 : (~3)(~5)"
    ),
    # Small families used for exhaustive sweeps in the audit and tests.
    "toggle": "x : (~y)\ny : (~x)",
    "repressilator": "x : (~z)\ny : (x)\nz : (y)",
    "cycle3": "x : (x)(~z)\ny : (x)(~y)\nz : (y)(~z)",
    "cycle4": "w : (~z)\nx : (w)\ny : (x)\nz : (y)(~w)",
}

#: Parameter-graph sizes asserted in the text, for the reproduction check.
CLAIMED_PARAMETER_GRAPH_SIZE: dict[str, int] = {
    "N2_a": 1600,
    "N2_b": 1600,
    "N3_A": 87_280_405_632,
    "N3_B": 3_600_000,
    "N5": 13_608_000_000,
    "N6_EMT": 4_429_771_960_320,
}


@lru_cache(maxsize=None)
def network(name: str) -> "DSGRN.Network":
    return DSGRN.Network(NETWORKS[name])


@lru_cache(maxsize=None)
def parameter_graph(name: str) -> "DSGRN.ParameterGraph":
    return DSGRN.ParameterGraph(network(name))


def parameter(name: str, index: int):
    return parameter_graph(name).parameter(index)


# ---------------------------------------------------------------------------
# Directly specified ramp systems (not generated by DSGRN)
# ---------------------------------------------------------------------------


@dataclasses.dataclass(frozen=True)
class RampSpec:
    """A ramp system given by its scalar ramp factors.

    ``nu``/``theta``/``h`` are ``dim x dim`` tables indexed ``[target][source]``:
    entry ``[k][n]`` holds the parameters of the ramp ``r_{k,n}(x_n)`` appearing
    in ``dot x_k``, or ``None`` when node ``n`` does not regulate node ``k``.

    This is the layout ``DSGRN_utils.WallLabelling.ramp_system_wall_labelling``
    expects, and it makes ``K(n) = sum_{m in target(n)} J_{m,n}``
    (``rem:K(n)``, RampSystemsv4.tex:254) a column sum.

    ``logic`` carries the interaction structure of ``def:interaction_function``:
    ``logic[k]`` is a list of factors, each a list of source indices, and

        E_k(x) = prod_factors ( sum_{n in factor} r_{k,n}(x_n) ).

    ``None`` means the type-I (single additive factor) reading, which is what
    both directly specified systems in the monograph use.
    """

    name: str
    source: str
    gamma: tuple[float, ...]
    nu: tuple[tuple[tuple[float, ...] | None, ...], ...]
    theta: tuple[tuple[tuple[float, ...] | None, ...], ...]
    h: tuple[tuple[tuple[float, ...] | None, ...], ...]
    #: Index set I claimed in the text, as tuples of allowed coordinates.
    claimed_index_set: tuple[int, ...] | None = None
    #: Interaction structure per node; None means one additive factor.
    logic: tuple[tuple[tuple[int, ...], ...], ...] | None = None

    @property
    def dim(self) -> int:
        return len(self.gamma)

    def _tables(self):
        """Empty lists in place of ``None`` for the DSGRN_utils entry point."""
        blank = lambda t: [[list(e) if e else [] for e in row] for row in t]
        return blank(self.nu), blank(self.theta), blank(self.h)

    def production(self, x):
        """``E(x)``: the interaction term, without the decay ``-gamma x``."""
        nu, theta, h = self._tables()

        def factor_sum(k, sources):
            return sum(
                ramp_function(x[n], nu[k][n], theta[k][n], h[k][n])
                for n in sources
                if theta[k][n]
            )

        out = []
        for k in range(self.dim):
            if self.logic is None:
                out.append(factor_sum(k, range(self.dim)))
                continue
            value = 1.0
            for factor in self.logic[k]:
                value *= factor_sum(k, factor)
            out.append(value)
        return out

    @classmethod
    def from_dsgrn(cls, network, parameter, h_bar: float, *, name: str = "", source: str = ""):
        """Build a ramp system realising a DSGRN parameter (``defn:DSGRN_ramp``).

        RampSystemsv4.tex:955-970: replace each switching function by a type-1
        ramp with the same plateaus --- ``nu = (l, l + delta)`` for activation and
        ``(l + delta, l)`` for repression --- keeping the DSGRN thresholds, and
        take ``gamma_n = 1`` as DSGRN normalises.

        A concrete point of the semi-algebraic region ``R(k)`` is drawn with
        ``DSGRN.ParameterSampler``.  ``prop:DSGRN_wall_constant`` says the induced
        wall labelling is constant on ``R(k) x H_0``, so any point of the region
        gives the same combinatorics; :func:`realises_dsgrn_labelling` checks
        that on the sample actually drawn.
        """
        import json as _json

        import DSGRN as _DSGRN

        sample = _json.loads(_DSGRN.ParameterSampler(network).sample(parameter))
        values = sample["Parameter"]
        dim = network.size()
        label = {k: network.name(k) for k in range(dim)}

        nu = [[None] * dim for _ in range(dim)]
        theta = [[None] * dim for _ in range(dim)]
        h = [[None] * dim for _ in range(dim)]
        for target in range(dim):
            for src in network.inputs(target):
                key = f"[{label[src]}->{label[target]}]"
                low = values["L" + key]
                high = values["U" + key]
                activating = network.interaction(src, target)
                nu[target][src] = (low, high) if activating else (high, low)
                theta[target][src] = (values["T" + key],)
                h[target][src] = (h_bar,)

        logic = tuple(
            tuple(tuple(factor) for factor in network.logic(k)) for k in range(dim)
        )
        return cls(
            name=name or f"dsgrn:{network.specification().strip()[:24]}",
            source=source,
            gamma=tuple(1.0 for _ in range(dim)),
            nu=tuple(tuple(row) for row in nu),
            theta=tuple(tuple(row) for row in theta),
            h=tuple(tuple(row) for row in h),
            logic=logic,
        )

    def vector_field(self, x):
        """``F_n(x) = -gamma_n x_n + E_n(x)`` (``defn:ramp_system``)."""
        e = self.production(x)
        return [-self.gamma[n] * x[n] + e[n] for n in range(self.dim)]

    @property
    def max_production(self) -> list[float]:
        """``M^E_n = max E_n``, respecting the interaction structure.

        Every ramp plateau is positive, so each factor sum is maximised
        independently and

            max E_n = prod_factors ( sum_{m in factor} max nu_{n,m} ).

        Summing the plateaus regardless of structure would be wrong for a
        type-II (product) interaction such as ``2 : (~1) 2``.
        """
        nu, theta, _h = self._tables()

        def factor_max(n, sources):
            return sum(max(nu[n][m]) for m in sources if theta[n][m])

        out = []
        for n in range(self.dim):
            if self.logic is None:
                out.append(factor_max(n, range(self.dim)))
                continue
            value = 1.0
            for factor in self.logic[n]:
                value *= factor_max(n, factor)
            out.append(value)
        return out

    @property
    def global_bound(self) -> list[float]:
        """``GB_n``, the outer sentinel threshold of ``defn:ramp-wall-labeling``.

        ``eq:GAB``: ``GB_n = max{ M^E_n / gamma_n, max ramp endpoint in n } + 1``.
        Note the two index roles: ``M^E_n`` is built from the ramps feeding node
        ``n`` (row ``n`` of the tables), while the ramp endpoints are those of
        the ramps *driven by* ``n`` (column ``n``), since those are the
        thresholds lying on the ``x_n`` axis.
        """
        _nu, theta, h = self._tables()
        production = self.max_production
        out = []
        for n in range(self.dim):
            endpoints = [
                t + hh
                for k in range(self.dim)
                for t, hh in zip(theta[k][n], h[k][n])
            ]
            out.append(
                max(production[n] / self.gamma[n], max(endpoints, default=0.0)) + 1.0
            )
        return out

    def wall_labelling(self, *, legacy: bool = False):
        """``(labelling, num_thresholds)`` via ``defn:ramp-wall-labeling``.

        The outer sentinel is ``GB_n``, as the definition states.  ``legacy=True``
        restores the ``theta + 10 h`` surrogate, which is h-dependent and loses
        strong dissipativity for small ``h``.
        """
        _nu, theta, h = self._tables()
        return ramp_system_wall_labelling(
            list(self.gamma),
            theta,
            h,
            self.production,
            global_bound=None if legacy else self.global_bound,
        )

    @property
    def num_thresholds(self) -> list[int]:
        """``K(n)``: the number of output thresholds of node ``n``."""
        _nu, theta, _h = self._tables()
        return [sum(len(theta[k][n]) for k in range(self.dim)) for n in range(self.dim)]

    @property
    def index_set(self) -> tuple[int, ...]:
        """``I = prod {0, ..., K(n)+1}``, reported as the top index per coordinate."""
        return tuple(k + 1 for k in self.num_thresholds)

    def with_uniform_width(self, h_bar: float) -> "RampSpec":
        """The same system with every half-width replaced by ``h_bar``.

        ``prop:smallh`` (RampSystemsv4.tex:624) proves nonemptiness of the
        width classes by exhibiting exactly such a uniform ``h``, and
        ``prop:wall-labeling-const`` (:490) says the wall labelling does not
        change with ``h`` inside ``H_0``.
        """
        scaled = tuple(
            tuple(tuple(h_bar for _ in e) if e else None for e in row) for row in self.h
        )
        return dataclasses.replace(
            self, name=f"{self.name}@h={h_bar:g}", h=scaled, claimed_index_set=None
        )


#: tab:parameters_van_der_pol_ramp_system, examples4.tex:857-869.
#: r_{1,1} is cubic-like; the rest are monotone with multiple ramps.
VAN_DER_POL = RampSpec(
    name="van_der_pol",
    source="examples4.tex:841 (ex:ramp_van_der_pol)",
    gamma=(2.0, 2.0),
    nu=(
        ((7, 3, 7, 3), (3.1, 4.9, 7.3)),
        ((7.5, 5.5, 4), (1.4, 5, 7.55, 9)),
    ),
    theta=(
        ((3, 5.1, 7.17), (5.3, 6.1)),
        ((4, 5.5), (4, 5.85, 7.55)),
    ),
    h=(
        ((0.15, 0.15, 0.15), (0.11, 0.11)),
        ((0.15, 0.15), (0.11, 0.11, 0.11)),
    ),
    claimed_index_set=(6, 6),
)

#: tab:parameters_ramp_system_intro_periodic, introduction6.tex:525-541.
#: The van der Pol planar system extended by a third coordinate.
#: ex:periodicOrbit3 (examples4.tex:307) states
#: I = {0..8} x {0..6} x {0,1,2,3}.
INTRO_PERIODIC = RampSpec(
    name="intro_periodic",
    source="introduction6.tex:498 (ex:introPeriodic) / examples4.tex:307 (ex:periodicOrbit3)",
    gamma=(2.0, 2.0, 2.0),
    nu=(
        ((7, 3, 7, 3), (3.1, 4.9, 7.3), None),
        ((7.5, 5.5, 4), (1.4, 5, 7.55, 9), None),
        ((3, 5, 6.9), None, (12, 5.2, 3)),
    ),
    theta=(
        ((3, 5.1, 7.17), (5.3, 6.1), None),
        ((4, 5.5), (4, 5.85, 7.55), None),
        ((2, 8), None, (4, 6)),
    ),
    h=(
        ((0.15, 0.15, 0.15), (0.11, 0.11), None),
        ((0.15, 0.15), (0.11, 0.11, 0.11), None),
        ((0.1, 0.1), None, (0.1, 0.1)),
    ),
    claimed_index_set=(8, 6, 3),
)

RAMP_SYSTEMS: dict[str, RampSpec] = {
    "van_der_pol": VAN_DER_POL,
    "intro_periodic": INTRO_PERIODIC,
}


def realises_dsgrn_labelling(name: str, index: int, h_bar: float, *, attempts: int = 6):
    """Build a ramp system for a DSGRN parameter and check it induces its labelling.

    ``prop:DSGRN_wall_constant`` (RampSystemsv4.tex:975) asserts the ramp induced
    wall labelling is constant on ``R(k) x H_0``, and in particular equals the
    one DSGRN computes combinatorially.  Returns ``(spec, matches)`` for the
    first sample whose labelling matches, or the last one tried.
    """
    import DSGRN

    net = network(name)
    par = parameter(name, index)
    # CubicalBlowupGraph rebuilds the network without self-edge blowup; the
    # combinatorial labelling to compare against is the one it uses.
    plain = DSGRN.Network(net.specification(), edge_blowup="none")
    plain_graph = DSGRN.ParameterGraph(plain)
    target = plain_graph.parameter(index).labelling()

    spec = None
    for _ in range(attempts):
        spec = RampSpec.from_dsgrn(net, par, h_bar,
                                   name=f"{name}[{index}]",
                                   source=f"DSGRN {name} node {index}")
        # The sampler draws thresholds anywhere in the region, so a fixed
        # half-width can overlap two windows and violate admissibility.  Shrink
        # it to a quarter of the smallest threshold gap on each axis.
        spec = spec.with_uniform_width(min(h_bar, 0.25 * _smallest_threshold_gap(spec)))
        try:
            labelling, _K = spec.wall_labelling()
        except ValueError:
            continue
        if labelling == target:
            return spec, True
    return spec, False


def _smallest_threshold_gap(spec: "RampSpec") -> float:
    """Smallest distance between consecutive output thresholds, over all axes."""
    _nu, theta, _h = spec._tables()
    best = float("inf")
    for n in range(spec.dim):
        pooled = sorted(t for k in range(spec.dim) for t in theta[k][n])
        best = min([best] + [b - a for a, b in zip(pooled, pooled[1:])])
        if pooled:
            best = min(best, pooled[0])  # keep the first window clear of 0
    return best if best != float("inf") else 1.0
